version: '2'
services:
  web:
    image: eboraas/laravel
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./src:/var/www/laravel/app
    environment:
      - APP_ENV=test
      - APP_DEBUG=true
      - APP_KEY=zQ,3]zy3f`zH:sEvi0HCnVYPw#*@/xUt
      
  db:
    image: mysql
#    volumes:
#      - ./data/:/var/lib/mysql
#      - ./data/mysql:/mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=password
