version: '2'
services:
  web:
    image: eboraas/laravel
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./src/app:/var/www/laravel/app
      - ./src/resources:/var/www/laravel/resources
      - ./src/database:/var/www/laravel/database
      - ./src/tests:/var/www/laravel/tests
      - ./src/.env:/var/www/laravel/.env
    links:
      - db
      
  db:
    image: mysql
    expose:
      - "3306"

#   volumes:
#      - ./testDB.sql:/docker-entrypoint-initdb.d/db.sql
#      - ./data/:/var/lib/mysql
#      - ./data/mysql:/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=forge
      - MYSQL_USER=forge
      - MYSQL_PASSWORD=password
